trigger:
  branches:
    include:
      - 'master'

  paths:
    exclude:
      - '/**/*.md'
      - '/**/*.markdown'
      - '/**/*.erb'

pr:
  branches:
    include:
      - '*'

  paths:
    exclude:
      - '/**/*.md'

jobs:
  - template: ./ci.yml
    parameters:
    - name: unittest
      type: boolean
      displayName: Run Unit Tests
      default: true

    - name: goVersions
      displayName: '1_16_2'
      type: string
      values:
        '1.16.2'


    - name: vmImages
      displayName: ubuntu_20_04
      type: string
      values:
        'ubuntu-20.04'
