dist: xenial
services:
  - docker
language: go
go:
  - "1.13.x"
"os":
  "linux"
branches:
  only:
    - master

env:
  global:
    GOFLAGS=-mod=vendor

install:
  # This script is used by the Travis build to install a cookie for
  # go.googlesource.com so rate limits are higher when using `go get` to fetch
  # packages that live there.
  # See: https://github.com/golang/go/issues/12933
  - bash scripts/gogetcookie.sh
  - make tools

jobs:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - name: "Verify Vendored Dependencies"
      script: make check-vendor-vs-mod
    - name: "Run Format Check"
      script: make fmtcheck
    - name: "Run Lint Check"
      script: make lint
    - name: "Run Unit Test"
      script: make test
    - name: "make website-lint"
      script: make website-lint
    - name: "make website-test"
      script: make website-test
    - name: "Run AccTests"
      script: make testacc
